(package "lsp-sonarlint"
         "0.0.1"
         "Emacs Sonarlint lsp client")

(package-file "lsp-sonarlint.el")

(files "languages" "languages/*/*.el" "server" "server/*")

(source "gnu")
(source "melpa")

(depends-on "emacs" "25")
(depends-on "dash" "2.12.0")
(depends-on "lsp-mode" "6.3")
(depends-on "ht" "2.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
